"""Add soft delete to ExpenseRecord

Revision ID: fa4199ad3467
Revises: a873b0a0388e
Create Date: 2026-02-11 18:59:18.029201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4199ad3467'
down_revision: Union[str, None] = 'a873b0a0388e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 三步骤添加 is_deleted 非空字段：1.添加可空字段 2.更新现有记录 3.修改为非空
    # 步骤1: 添加 is_deleted 字段，允许NULL
    op.add_column('expense_record', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否已删除'))
    
    # 步骤2: 更新现有记录，设置默认值 False
    op.execute("UPDATE expense_record SET is_deleted = false WHERE is_deleted IS NULL")
    
    # 步骤3: 修改字段为NOT NULL
    op.alter_column('expense_record', 'is_deleted', nullable=False)
    
    # 添加 deleted_at 字段（可以为空）
    op.add_column('expense_record', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'))
    
    # op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)  # 索引已存在，注释掉
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_product_category_id'), table_name='product')  # 索引操作已注释，对应删除也注释
    op.drop_column('expense_record', 'deleted_at')
    op.drop_column('expense_record', 'is_deleted')
    # ### end Alembic commands ###
