"""Add cost_behavior to ExpenseType for CVP analysis

Revision ID: a873b0a0388e
Revises: f2d0071a8a65
Create Date: 2026-02-11 18:16:58.786498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a873b0a0388e'
down_revision: Union[str, None] = 'f2d0071a8a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='资源名称或操作对象',
               existing_comment='资源类型',
               existing_nullable=False)
    op.alter_column('audit_log', 'method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP方法：GET/POST/PUT/DELETE等',
               existing_comment='HTTP 方法',
               existing_nullable=True)
    op.alter_column('audit_log', 'path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_comment='请求路径',
               existing_nullable=True)
    op.alter_column('audit_log', 'status_code',
               existing_type=sa.INTEGER(),
               comment='HTTP状态码',
               existing_comment='响应状态码',
               existing_nullable=True)
    # 三步添加非空字段：1.添加可空字段 2.更新现有记录 3.修改为非空
    # 步骤1: 添加字段，允许NULL
    op.add_column('expense_type', sa.Column('cost_behavior', sa.String(length=20), nullable=True, comment='成本习性（fixed=固定成本, variable=变动成本）'))
    
    # 步骤2: 更新现有记录，设置默认值
    op.execute("UPDATE expense_type SET cost_behavior = 'variable' WHERE cost_behavior IS NULL")
    
    # 步骤3: 修改字段为NOT NULL
    op.alter_column('expense_type', 'cost_behavior', nullable=False)
    # op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)  # 索引已存在，注释掉
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_product_category_id'), table_name='product')  # 索引操作已注释，对应删除也注释
    op.drop_column('expense_type', 'cost_behavior')
    op.alter_column('audit_log', 'status_code',
               existing_type=sa.INTEGER(),
               comment='响应状态码',
               existing_comment='HTTP状态码',
               existing_nullable=True)
    op.alter_column('audit_log', 'path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_comment='请求路径',
               existing_nullable=True)
    op.alter_column('audit_log', 'method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP 方法',
               existing_comment='HTTP方法：GET/POST/PUT/DELETE等',
               existing_nullable=True)
    op.alter_column('audit_log', 'resource',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment='资源类型',
               existing_comment='资源名称或操作对象',
               existing_nullable=False)
    # ### end Alembic commands ###
