"""Add budget table

Revision ID: f2d0071a8a65
Revises: 0004_user_store_permissions
Create Date: 2026-02-11 10:11:23.666398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d0071a8a65'
down_revision: Union[str, None] = '0004_user_store_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除子表 data_import_job_error（有外键依赖父表）
    op.drop_index('ix_data_import_job_error_id', table_name='data_import_job_error')
    op.drop_index('ix_import_job_error_job_id', table_name='data_import_job_error')
    op.drop_index('ix_import_job_error_row_no', table_name='data_import_job_error')
    op.drop_table('data_import_job_error')
    # 再删除父表 data_import_job
    op.drop_index('ix_data_import_job_id', table_name='data_import_job')
    op.drop_index('ix_import_job_created_at', table_name='data_import_job')
    op.drop_index('ix_import_job_created_by', table_name='data_import_job')
    op.drop_index('ix_import_job_status', table_name='data_import_job')
    op.drop_index('ix_import_job_target_type', table_name='data_import_job')
    op.drop_table('data_import_job')
    op.drop_index('ix_budgets_id', table_name='budgets')
    op.drop_table('budgets')
    
    # 在设置 NOT NULL 约束之前，先更新 audit_log 中的 NULL 值
    op.execute("UPDATE audit_log SET username = 'system' WHERE username IS NULL")
    op.execute("UPDATE audit_log SET resource = 'unknown' WHERE resource IS NULL")
    
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作用户ID',
               existing_comment='用户ID',
               existing_nullable=True)
    op.alter_column('audit_log', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='操作用户名（冗余存储，防止用户删除后无法追溯）',
               existing_comment='用户名（快照）')
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型：login/logout/create_expense/update_expense/delete_expense/rebuild_kpi等',
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='资源类型')
    
    # 在转换类型之前，清理不是数字的 resource_id 值
    op.execute("""
        UPDATE audit_log 
        SET resource_id = NULL 
        WHERE resource_id !~ '^[0-9]+$' OR resource_id = ''
    """)
    
    op.alter_column('audit_log', 'resource_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               postgresql_using='resource_id::integer',
               existing_comment='资源ID',
               existing_nullable=True)
    op.alter_column('audit_log', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               comment='客户端IP地址（支持IPv6）',
               existing_comment='IP 地址',
               existing_nullable=True)
    op.alter_column('audit_log', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               comment='客户端User-Agent',
               existing_comment='User Agent',
               existing_nullable=True)
    op.alter_column('audit_log', 'detail',
               existing_type=sa.TEXT(),
               comment='操作详情（JSON格式），不包含敏感信息如密码',
               existing_comment='操作详情（JSON）',
               existing_nullable=True)
    op.alter_column('audit_log', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息（仅在失败时记录）',
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='资源类型：expense/kpi/order/store/user等',
               existing_nullable=True)
    op.alter_column('audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False,
               comment='操作结果：success/failure/error')
    op.alter_column('audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False,
               comment='更新时间')
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index('ix_audit_log_resource_type', 'audit_log', ['resource_type'], unique=False)
    op.alter_column('expense_record', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态（draft/submitted/approved/rejected/paid）',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('expense_record', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('expense_record', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_expense_record_id'), 'expense_record', ['id'], unique=False)
    op.alter_column('expense_type', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='费用类别（operating/marketing/administrative/other）',
               existing_comment='费用类别',
               existing_nullable=False)
    op.alter_column('expense_type', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('expense_type', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_expense_type_id'), 'expense_type', ['id'], unique=False)
    op.alter_column('kpi_daily_store', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('kpi_daily_store', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_kpi_daily_store_id'), 'kpi_daily_store', ['id'], unique=False)
    op.alter_column('order_header', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='订单渠道（dine_in/takeout/delivery/online）',
               existing_comment='订单渠道',
               existing_nullable=False)
    op.alter_column('order_header', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               comment='支付方式（cash/alipay/wechat/card/other）',
               existing_comment='支付方式',
               existing_nullable=False)
    op.alter_column('order_header', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='订单状态（pending/confirmed/preparing/completed/cancelled/refunded）',
               existing_comment='订单状态',
               existing_nullable=False)
    op.alter_column('order_header', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('order_header', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_order_header_id'), 'order_header', ['id'], unique=False)
    op.alter_column('order_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('order_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.alter_column('permission', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('permission', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('product', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否已删除',
               existing_nullable=False)
    op.alter_column('product', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='删除时间',
               existing_nullable=True)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.alter_column('product_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('product_category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_product_category_id'), 'product_category', ['id'], unique=False)
    op.drop_column('product_category', 'is_deleted')
    op.drop_column('product_category', 'deleted_at')
    op.alter_column('role', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('role', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.alter_column('store', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('store', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('store', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否已删除',
               existing_nullable=False)
    op.alter_column('store', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='删除时间',
               existing_nullable=True)
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.alter_column('store', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('store', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='是否已删除',
               existing_nullable=False)
    op.alter_column('store', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('store', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.alter_column('role', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('role', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.add_column('product_category', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('product_category', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_product_category_id'), table_name='product_category')
    op.alter_column('product_category', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('product_category', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.alter_column('product', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('product', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否已删除',
               existing_nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.alter_column('permission', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('permission', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.alter_column('order_item', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('order_item', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_order_header_id'), table_name='order_header')
    op.alter_column('order_header', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('order_header', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('order_header', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='订单状态',
               existing_comment='订单状态（pending/confirmed/preparing/completed/cancelled/refunded）',
               existing_nullable=False)
    op.alter_column('order_header', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               comment='支付方式',
               existing_comment='支付方式（cash/alipay/wechat/card/other）',
               existing_nullable=False)
    op.alter_column('order_header', 'channel',
               existing_type=sa.VARCHAR(length=20),
               comment='订单渠道',
               existing_comment='订单渠道（dine_in/takeout/delivery/online）',
               existing_nullable=False)
    op.drop_index(op.f('ix_kpi_daily_store_id'), table_name='kpi_daily_store')
    op.alter_column('kpi_daily_store', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('kpi_daily_store', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_expense_type_id'), table_name='expense_type')
    op.alter_column('expense_type', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('expense_type', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('expense_type', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='费用类别',
               existing_comment='费用类别（operating/marketing/administrative/other）',
               existing_nullable=False)
    op.drop_index(op.f('ix_expense_record_id'), table_name='expense_record')
    op.alter_column('expense_record', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('expense_record', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('expense_record', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态',
               existing_comment='状态（draft/submitted/approved/rejected/paid）',
               existing_nullable=False)
    op.drop_index('ix_audit_log_resource_type', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.alter_column('audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               comment=None,
               existing_comment='更新时间')
    op.alter_column('audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'success'::character varying"),
               nullable=True,
               comment=None,
               existing_comment='操作结果：success/failure/error')
    op.alter_column('audit_log', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源类型：expense/kpi/order/store/user等',
               existing_nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('audit_log', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_comment='错误信息（仅在失败时记录）',
               existing_nullable=True)
    op.alter_column('audit_log', 'detail',
               existing_type=sa.TEXT(),
               comment='操作详情（JSON）',
               existing_comment='操作详情（JSON格式），不包含敏感信息如密码',
               existing_nullable=True)
    op.alter_column('audit_log', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               comment='User Agent',
               existing_comment='客户端User-Agent',
               existing_nullable=True)
    op.alter_column('audit_log', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               comment='IP 地址',
               existing_comment='客户端IP地址（支持IPv6）',
               existing_nullable=True)
    op.alter_column('audit_log', 'resource_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_comment='资源ID',
               existing_nullable=True)
    op.alter_column('audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='资源类型')
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型',
               existing_comment='操作类型：login/logout/create_expense/update_expense/delete_expense/rebuild_kpi等',
               existing_nullable=False)
    op.alter_column('audit_log', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='用户名（快照）',
               existing_comment='操作用户名（冗余存储，防止用户删除后无法追溯）')
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_comment='操作用户ID',
               existing_nullable=True)
    op.create_table('budgets',
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='门店ID'),
    sa.Column('expense_type_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='费用科目ID'),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False, comment='年份'),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False, comment='月份'),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, comment='预算金额'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建用户ID'),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='更新用户ID'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='budgets_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['expense_type_id'], ['expense_type.id'], name='budgets_expense_type_id_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name='budgets_store_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='budgets_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budgets_pkey'),
    sa.UniqueConstraint('store_id', 'expense_type_id', 'year', 'month', name='uq_budget_store_expense_date')
    )
    op.create_index('ix_budgets_id', 'budgets', ['id'], unique=False)
    # 先创建父表 data_import_job
    op.create_table('data_import_job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('job_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='任务名称'),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='源文件类型: excel/csv'),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='目标类型: orders/expense_records/stores/expense_types'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='任务状态: pending/running/success/partial_fail/fail'),
    sa.Column('file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False, comment='文件存储路径'),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=False, comment='总行数'),
    sa.Column('success_rows', sa.INTEGER(), autoincrement=False, nullable=False, comment='成功行数'),
    sa.Column('fail_rows', sa.INTEGER(), autoincrement=False, nullable=False, comment='失败行数'),
    sa.Column('error_report_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='错误报告文件路径'),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='创建人ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.CheckConstraint('fail_rows >= 0', name='ck_import_job_fail_rows'),
    sa.CheckConstraint('success_rows >= 0', name='ck_import_job_success_rows'),
    sa.CheckConstraint('total_rows >= 0', name='ck_import_job_total_rows'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='data_import_job_created_by_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='data_import_job_pkey'),
    comment='数据导入任务表'
    )
    op.create_index('ix_import_job_target_type', 'data_import_job', ['target_type'], unique=False)
    op.create_index('ix_import_job_status', 'data_import_job', ['status'], unique=False)
    op.create_index('ix_import_job_created_by', 'data_import_job', ['created_by_id'], unique=False)
    op.create_index('ix_import_job_created_at', 'data_import_job', ['created_at'], unique=False)
    op.create_index('ix_data_import_job_id', 'data_import_job', ['id'], unique=False)
    # 再创建子表 data_import_job_error（依赖父表）
    op.create_table('data_import_job_error',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='任务ID'),
    sa.Column('row_no', sa.INTEGER(), autoincrement=False, nullable=False, comment='行号'),
    sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='错误字段'),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False, comment='错误消息'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='原始数据（JSON格式）'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['job_id'], ['data_import_job.id'], name='data_import_job_error_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='data_import_job_error_pkey'),
    comment='数据导入错误记录表'
    )
    op.create_index('ix_import_job_error_row_no', 'data_import_job_error', ['row_no'], unique=False)
    op.create_index('ix_import_job_error_job_id', 'data_import_job_error', ['job_id'], unique=False)
    op.create_index('ix_data_import_job_error_id', 'data_import_job_error', ['id'], unique=False)
    # ### end Alembic commands ###
